### ISSUE TITLE
Mode of the payment

### ISSUE THREAD

**Issue by shankarbhattarai123** [wdtheprovider/onepref#2]
I just integrated the IAP using this package and i checked all the feature using test mode but i didn't find any way to make purchase live mode from test mode.

**Comment by wdtheprovider** [comment]
Your users will see the live mode when they download your app, you are seeing the test mode because your gmail is in the testing policy list. to verify this ask one of your friends to download your app and see.

**Comment by shankarbhattarai123** [comment]
issue solved. Thank you so much.

**Comment by shankarbhattarai123** [comment]
Hello sir, products and subscriptions list are shown in some mobile and not shown in some mobile. These all app are downloaded from playstore directly.What could be the problem? Anything i have to setup in play console for this?
